CREATE TABLE IF NOT EXISTS USERLOGIN  
 ( 
 USER_ID INTEGER NOT NULL, 
 USER_NAME CHARACTER VARYING(20)  NOT NULL, 
 PASSWORD CHARACTER VARYING(20) ,  
 CONSTRAINT PK_CUSTID PRIMARY KEY (USER_ID) 
  ) 
 WITH ( 
   OIDS = FALSE 
 ); 
 
 
 ALTER TABLE USERLOGIN 
 OWNER TO POSTGRES; 
 
 
 INSERT INTO	 USERLOGIN ("USER_ID", "USER_NAME", "password") VALUES 
 (1,	'Rama',	'Sita'), 
 (2,	'Lakshmana','Hanuman');